In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

In [3]:
!pip install --upgrade numpy


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip


In [4]:
import numpy as np
np.__version__

'1.21.6'

## Scalar

In [5]:
a = 50
print(type(a))
a = np.array(50)
print(type(a))



<class 'int'>
<class 'numpy.ndarray'>


In [6]:
a = np.array(50)

print(a)
print(type(a))
print(a.ndim)# 0
print(a.size)


50
<class 'numpy.ndarray'>
0
1


# Vector

In [7]:
a = np.array([1,7,9,9,20])

print(a)
print(type(a))
print(a.ndim)# 1
print(a.size)


[ 1  7  9  9 20]
<class 'numpy.ndarray'>
1
5


# Matrix

In [8]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])


display(a)
display(type(a))
display(a.ndim)# 2
display(a.size)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy.ndarray

2

9

# python list vs numpy array

In [9]:
%%time
display([i+5 for  i in range(1,1000000)])

[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


CPU times: user 66.4 ms, sys: 27.5 ms, total: 93.9 ms
Wall time: 98.3 ms


In [10]:
%%time
np.arange(1,1000000) + 5

CPU times: user 1.71 ms, sys: 12.3 ms, total: 14 ms
Wall time: 12.8 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [11]:
26/161*100

16.149068322981368

# Easy to use

In [12]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

display(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
for ridx,_ in enumerate(a):
    for cidx,_ in enumerate(a[ridx]):
#         print(ridx,cidx, sep=",")
        a[ridx][cidx] += 5
    
a    

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]

In [14]:
a = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])

a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
#rows, columns
a.shape

(3, 3)

# Now apply some code with offical documentation 

In [16]:
a = np.arange(1,11)
#num of elements
print(a.shape)

(10,)


In [17]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
a.shape
#slide,row,columns

(3, 3, 3)

In [22]:
a = np.arange(4*5*3).reshape(4,5,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [23]:
a.shape

(4, 5, 3)

In [20]:
del a

In [ ]:
a[-1]

# How to create a basic array


In [26]:
a = np.array([1,2,23,3,5])
print(type(a))

<class 'numpy.ndarray'>


In [27]:
a = np.zeros((10,10))
print(type(a))
a

<class 'numpy.ndarray'>


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
a = np.ones((10,10))
print(type(a))
a

<class 'numpy.ndarray'>


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
a = np.empty((10,10))
print(type(a))
a

<class 'numpy.ndarray'>


array([[0.00000000e+000, 0.00000000e+000, 3.78948350e-321,
                    nan, 1.50008929e+248, 6.99196220e+228,
        2.59441754e+161, 1.16243294e-028, 9.16281386e-072,
        7.16535896e-090],
       [4.47593816e-091, 4.47593816e-091, 4.47593816e-091,
        4.47593816e-091, 4.47593816e-091, 4.47593816e-091,
        4.47593816e-091, 4.47593816e-091, 1.61410559e+132,
        2.11211249e+257],
       [6.60925411e-062, 2.85340344e+242, 9.16281387e-072,
        6.01347173e-154, 6.01347002e-154, 6.01347002e-154,
        5.26742387e+170, 6.65370744e+217, 2.51516048e+180,
        1.69592889e-152],
       [1.04914410e-153, 1.61410559e+132, 3.13435284e+233,
        7.28079528e+223, 3.61005580e+174, 4.03410073e+175,
        1.42137851e-076, 7.26610491e+223, 1.61410559e+132,
        5.54070841e+228],
       [2.95154216e-075, 3.06370797e-057, 1.61410559e+132,
        1.42137876e-076, 1.00385544e+218, 1.24478027e+136,
        1.35301660e-023, 1.42137836e-076, 2.13067624e+257,
        1.6

In [29]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Linspace

In [35]:
a = np.linspace(1,2,5)
print(len(a))
a

5


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
a = np.ones((2,3))
print(a.dtype)
a

float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
a = np.ones((2,3),dtype=np.int64)
print(a.dtype)
a

int64


array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
a = np.ones((2,3),dtype=str)
print(a.dtype)
a

<U1


array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

# Sort

In [47]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.random.randint(1,100, size=(10,10))
a

array([[14, 83, 95, 77, 94, 12,  4, 95, 21, 97],
       [61, 56, 77, 55, 18, 64, 40,  3, 12, 29],
       [93, 82, 71, 72, 60, 68, 95, 84, 95, 53],
       [ 9, 17, 17, 53, 74, 70, 30, 28, 44, 44],
       [85, 49, 31, 61, 57, 16,  6, 68, 57, 81],
       [70, 38, 89, 29, 60, 86, 45, 19, 15,  4],
       [62, 46, 43, 68, 57, 30, 74, 28,  9, 49],
       [17, 11, 43, 86, 31, 98, 93, 30, 54, 60],
       [72, 25, 45, 71, 30, 68, 55, 37, 43, 64],
       [29, 11, 76, 86, 30, 85, 15, 73, 12, 69]])

In [46]:
np.sort(a, axis=-1)

array([[ 4, 12, 14, 21, 77, 83, 94, 95, 95, 97],
       [ 3, 12, 18, 29, 40, 55, 56, 61, 64, 77],
       [53, 60, 68, 71, 72, 82, 84, 93, 95, 95],
       [ 9, 17, 17, 28, 30, 44, 44, 53, 70, 74],
       [ 6, 16, 31, 49, 57, 57, 61, 68, 81, 85],
       [ 4, 15, 19, 29, 38, 45, 60, 70, 86, 89],
       [ 9, 28, 30, 43, 46, 49, 57, 62, 68, 74],
       [11, 17, 30, 31, 43, 54, 60, 86, 93, 98],
       [25, 30, 37, 43, 45, 55, 64, 68, 71, 72],
       [11, 12, 15, 29, 30, 69, 73, 76, 85, 86]])

In [48]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [50]:
np.argsort(arr)
#  0  1  2  3  4  5  6  7
# [2, 1, 5, 3, 7, 4, 6, 8]

array([1, 0, 3, 5, 2, 6, 4, 7])

NameError: name 'np' is not defined