# pandas
* series
* dataframe

In [3]:
l1 = ['a','b','c','d']
display(l1)
display(type(l1))

['a', 'b', 'c', 'd']

list

In [2]:
import pandas as pd

In [5]:
# list

l1 = ['a','b','c','d']
display(l1)
display(type(l1))
print('============')
s1 = pd.Series(l1)
display(s1)
display(type(s1))

['a', 'b', 'c', 'd']

list

0    a
1    b
2    c
3    d
dtype: object

pandas.core.series.Series

In [6]:
s1

0    a
1    b
2    c
3    d
dtype: object

In [8]:
s2 = pd.Series([1,2,3,5])
s2

0    1
1    2
2    3
3    5
dtype: int64

In [7]:
l1

['a', 'b', 'c', 'd']

In [9]:
# tuple
t1 = (1,7,8,9,10.2,78)
s1 = pd.Series(t1)

display(s1)
display(type(s1))

0     1.0
1     7.0
2     8.0
3     9.0
4    10.2
5    78.0
dtype: float64

pandas.core.series.Series

In [10]:
# Dictionary
d1 = {
    'a':1,
    'b': 'pakistan',
    'c':20,
    'd':100
}

s1 = pd.Series(d1)
s1

a           1
b    pakistan
c          20
d         100
dtype: object

In [11]:
k = ['a','b','c']
v = [100,200,300]


s1 = pd.Series(data=v, index=k)
display(s1)
s1 = pd.Series(v,k)
display(s1)

a    100
b    200
c    300
dtype: int64

a    100
b    200
c    300
dtype: int64

In [17]:
s2 = pd.Series([1,2,3,5], name='rollnumber')
s2

0    1
1    2
2    3
3    5
Name: rollnumber, dtype: int64

In [18]:
display(s2.index)
display(s2.values)
display(s2.name)

RangeIndex(start=0, stop=4, step=1)

array([1, 2, 3, 5])

'rollnumber'

In [ ]:
create series 
* list
* tuple
* dictionary
* key,value pass in index and value argument

# DataFrame

In [20]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

display(data)
print(type(data))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

<class 'list'>


In [22]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [44]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data,
                  columns = ['id','name','course']) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


id  name  course
0   1     2       3
1   4     5       6
2   7     8       9

In [45]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data,
                  columns = ['id','name','course'],
                 index=['a','b','c']) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


id  name  course
a   1     2       3
b   4     5       6
c   7     8       9

In [23]:
data = ((1,2,3),
       (4,5,6),
       (7,8,9))

df = pd.DataFrame(data) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [25]:
import numpy as np

data = np.random.randint(1,100, size=(10,10))
data

array([[ 4,  9, 50, 95,  7, 63, 10, 84, 20, 30],
       [20, 25, 93, 87, 61, 35, 33, 12, 18,  4],
       [66, 56, 61, 47, 17, 28, 41, 73, 99, 19],
       [ 6, 61, 96, 92, 54, 71, 77, 60, 26, 48],
       [79, 25, 95, 35, 34, 83, 52, 30, 92, 61],
       [65, 26, 38, 53, 29, 51,  6, 20, 99, 40],
       [83, 98, 89, 86, 63, 28, 12, 31, 56, 54],
       [81, 42, 38, 84, 62, 66, 82,  5, 14, 88],
       [77, 62, 81, 17, 94,  7, 11, 95, 40, 67],
       [11, 67, 72, 46, 76, 89, 71, 11,  8, 77]])

In [27]:
data = np.random.randint(1,100, size=(10,10))

df = pd.DataFrame(data)
df

0   1   2   3   4   5   6   7   8   9
0  99   7  58   9   4   5  83  19  76   8
1  71  53   9  50  98  86  88  99  73  38
2  73  70  21  21  76  47  64  91  42  41
3  50  84  53  90  84  50   3  33   7  25
4  97  54  63  51  91  55   2   8  11  34
5  14  78  17   7   2  87  10  30  47  63
6  99  15  20  10  10  82  45  88  47  26
7  12  55  98   2  46  33  87  50  17  54
8   6  71  61  29  71  62  81  61   8   9
9  52  46  38  88  53  92  22  91  71   7

# create dataframe with dictionary

In [47]:
d1 = {
    "id":[1,2,3],
    "name":['Hamza',"Asif",'Junaid'],
    'NED course':['AI',"DataVisualization",'DS']
}
display(d1)

df = pd.DataFrame(d1)
df

{'id': [1, 2, 3],
 'name': ['Hamza', 'Asif', 'Junaid'],
 'NED course': ['AI', 'DataVisualization', 'DS']}

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

# extract columns from dataframe

* dataframe.column_name
    * space not allowed in column name
    * we can't add new column
* dataframe['column name']

In [48]:
display(df)
print(type(df))
sid = df.id

print(type(sid), )
sid

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


0    1
1    2
2    3
Name: id, dtype: int64

In [49]:
display(df)

sname = df.name

sname

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

0     Hamza
1      Asif
2    Junaid
Name: name, dtype: object

In [50]:
display(df)

scourse = df.NED course
scourse


SyntaxError: invalid syntax (<ipython-input-50-9dd94fc3cd02>, line 3)

In [51]:
display(df)

scourse = df['NED course']
scourse

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

0                   AI
1    DataVisualization
2                   DS
Name: NED course, dtype: object

In [52]:
df.Timing = '1PM to 3PM' # add new column

df

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

In [53]:
df.id = [100,200,300] # add new column

df

id    name         NED course
0  100   Hamza                 AI
1  200    Asif  DataVisualization
2  300  Junaid                 DS

In [54]:
df['Timing'] = "1 PM to 3PM"
df

id    name         NED course       Timing
0  100   Hamza                 AI  1 PM to 3PM
1  200    Asif  DataVisualization  1 PM to 3PM
2  300  Junaid                 DS  1 PM to 3PM

In [55]:
df.values

array([[100, 'Hamza', 'AI', '1 PM to 3PM'],
       [200, 'Asif', 'DataVisualization', '1 PM to 3PM'],
       [300, 'Junaid', 'DS', '1 PM to 3PM']], dtype=object)

In [56]:
df.columns

Index(['id', 'name', 'NED course', 'Timing'], dtype='object')

In [57]:
df.index

RangeIndex(start=0, stop=3, step=1)

# extrace morethan one columns

In [ ]:
dataframe[list_of_columns]

In [58]:
df.columns

Index(['id', 'name', 'NED course', 'Timing'], dtype='object')

In [61]:
df[['Timing','id','name']]

Timing   id    name
0  1 PM to 3PM  100   Hamza
1  1 PM to 3PM  200    Asif
2  1 PM to 3PM  300  Junaid

In [62]:
cols = ['Timing','id','name']
df[cols]

Timing   id    name
0  1 PM to 3PM  100   Hamza
1  1 PM to 3PM  200    Asif
2  1 PM to 3PM  300  Junaid

In [63]:
s1 = df.id
type(s1)

pandas.core.series.Series

In [67]:
s1 = df['id']
type(s1)

pandas.core.series.Series

In [68]:
s1 = df[['id']]
type(s1)

pandas.core.frame.DataFrame

In [65]:
df

id    name         NED course       Timing
0  100   Hamza                 AI  1 PM to 3PM
1  200    Asif  DataVisualization  1 PM to 3PM
2  300  Junaid                 DS  1 PM to 3PM

In [66]:
df1 = df[['NED course','id']]
print(type(df1))

<class 'pandas.core.frame.DataFrame'>


# Create data using numpy pandas

In [75]:
df1 = pd.DataFrame(
    {
        "rollno":np.arange(1,101),
        'name': np.random.choice(['Ali','Hamza','Junaid',"Asif"],100),
        'fname': np.random.choice(['Ali','Hamza','Junaid',"Asif"],100),
        'course': np.random.choice(['AI','DS','ML',"Blockchain"],100),
        's1': np.random.randint(1,100, 100),
        's2': np.random.randint(1,100, 100),
        's3': np.random.randint(1,100, 100),
        's4': np.random.randint(1,100, 100),
        's5': np.random.randint(1,100, 100),

    }
)

df1

rollno    name   fname      course  s1  s2  s3  s4  s5
0        1  Junaid     Ali          AI  30  51  82  68  34
1        2     Ali    Asif          AI  84  62  61  58  41
2        3  Junaid   Hamza          ML  20  94  77  42  90
3        4    Asif    Asif          DS  80  29  27  13  76
4        5     Ali   Hamza          AI  74  72  87  20  70
..     ...     ...     ...         ...  ..  ..  ..  ..  ..
95      96   Hamza   Hamza  Blockchain  96  27  69  91   1
96      97     Ali   Hamza          ML  95  79  55  30  46
97      98   Hamza  Junaid          ML  81  31  31  67  99
98      99    Asif     Ali          ML  88  51  88  44  52
99     100  Junaid     Ali          ML  32  26  79   6  93

[100 rows x 9 columns]